### ISSUE TITLE
New website proposal

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/developers.laboratoria.la#10]
Following up on the [conversation started in the forum](http://community.laboratoria.la/t/new-website-for-the-devschapter/443/3), I'm opening this issue to start assigning people and get the ball rolling...

So far @gmoura and @mikenieva have volunteered. Who else wants to join the effort?

The next step would be for the volunteers to put together a proposal including either a prototype or storyboard, as well as links to other sites that we can use as reference/inspiration. This proposal should take into consideration the content architecture proposed in the [`README.md`](https://github.com/Laboratoria/developers.laboratoria.la/blob/master/README.md) file and our [Visual Identity Guide](https://sites.google.com/laboratoria.la/wiki/marca) and the fact that we normally use the "magenta" version of the logo when referring to the Developers Chapter.

![laboratoria_isotipo_rgb-03](https://user-images.githubusercontent.com/110297/42234628-c69a11c4-7eba-11e8-868c-ca0162b6dfd9.png)

cc/ @Laboratoria/developers

**Comment by gmoura** [comment]
Hi guys!  

I created some issues related to each content we need create for our new website

##### This one is about **CSS Style Guide/Standards** : #12 

##### This one is  about **HTML Style guide/Standards**: #14 

##### This one is about **Github workflow**: #13 

##### This one is about **Our Stack**: #16 

##### This one is about **Our Products**: #15

**Comment by memecast** [comment]
Great @gmoura I will check it out to start helping :D Have a great day !
