### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/developers.laboratoria.la#23]
@danielasarzosa earlier wrote to me asking for an inventory of _plugins_, _cookies_ and _external 3rd party services_ (ie: payment gateways, ...) used on our web platform. This is needed in order to complete our Privacy Policy, which is being worked on with the support of a 3rd party consultant.

I believe this affects all public facing "web properties", which means that we will need collaboration from a few people in order to get this done. For reference, I believe this is the list of web properties (if I'm missing something please let me know): 

| URL | Admin | Host | Cookies | 3rd party services |
| --- | --- | --- | --- | --- |
| http://www.laboratoria.la/ | @coloradomarin | Instapage? | ? | ? |
| http://empresas.laboratoria.la/ | @coloradomarin @claudiaalf | Instapage? | ? | ? |
| http://convocatoria.laboratoria.la/ | @danielasarzosa | Instapage? | ? | ? |
| http://talento.laboratoria.la/ | @andreamarianalm | Instapage? | ? | ? |
| https://app.talento.laboratoria.la/ | @gmoura | Firebase  | ? | ? |
| https://lms.laboratoria.la/ | @ivandevp | Firebase | Google Analytics | Not yet? |
| https://api.laboratoria.la/ | @lupomontero | Firebase | n/a | Mandrill, Typeform, ... |
| http://community.laboratoria.la/ | @lupomontero @merunga | Discourse on GCP | Auth, Google Analytics | ? |

## Plugins

As far as I know we don't use any _plugins_, at least what would be consider a _browser plugin_. @danielasarzosa, can you double check exactly what they mean by _plugins_?

## Cookies

I only have knowledge of the LMS and API. The LMS uses Google Analytics, and as such, the site will set some GA cookies. We also use Hotjar, but looking at the browser's dev tools I can not see any HotJar cookies being set. The site also provides authentication via the Firebase SDK, which doesn't use cookies (at least in modern browsers with support for localStorage). On the other hand, the API does not set any cookies as far as I know (or at least it shouldn't :see_no_evil:).

## 3rd party services

* Firestore database?
* Mandrill/MailChimp for email delivery
* Typeform for admission forms (@danielasarzosa)
* Platzi? (@ivandevp)
* ...?

We do not use a payment gateway yet, but we have discussed several times adding one in the future so that we can integrate student payments, and eventually paid courses, subscrptions, standard billing/invoicing, ...

### HTTPS

It is worth noting that the Firebase hosted sites are served over HTTPS, which in my view should be standard for all web products (for security, trust and SEO). I do not know whether Instapage offers free generic SSL certs, but we should consider options.

### Data warehousing

From the point of view of our web apps, we are storing data (user data) in:

* Firebase's Firestore database
* Lots of Google Sheets!
* Typeform
* ?

***

It is also worth mentioning that the lack of a comprehensive Privacy Policy was a blocking issue when we implemented Facebook SignIn/SignUp on the LMS:

https://github.com/Laboratoria/lms.laboratoria.la/issues/157

***

All help clarifying all the question marks (`?`) is welcome :wink:

**Comment by claudiaalf** [comment]
Hi guys, for Corporate Training, we collect these info:

Web Laboratoria
- cookies for Google Analytics
- contact form
- cookies for retargeting ads

Promoter.io / Typeform
- We collect data (emails) for NPS
