### ISSUE TITLE
Propuesta para el Chapter de Developers

### ISSUE THREAD

**Issue by lizzie136** [Laboratoria/developers.laboratoria.la#24]
## PROPOSAL FOR THE DEVELOPER'S CHAPTER

Un poco de contexto. Hace un par de días decidimos tomar el ownership del chapter de developers.
Para ellos comenzamos con una retrospectiva un poco particular: 

#### Participantes: 
@shirley-suarez , @lizzie136 , @Jonhks , @mikenieva 

### Lo que nos gustó: 
- Presentar nuestros proyectos
- Recibir feedback
- Las cosas que aprendimos
- Ver código de otras personas
- Tratar temas del aula, como estrategias y experiencias.

### Lo que no nos gustó tanto: 
- A veces da la sensación de comunicación jerárquica. 
- Nivel técnico abrumador
- Que no quedó tan claro para qué era el chapter
- Que nos clasificaran en niveles por lo que presentamos sin comunicarnos. 
- Que no se de voz al chat de youtube
- Que no haya agenda
- Tiempos no medidos, dos horas es mucho!
- No se respeto/ se confundió el alcance de los proyectos y de las presentaciones. 

### Que nos gustaría intentar: 
- enfocar: coaches y developers en momentos distintos. 
- chapter lead, x sede, x sesión
- moderador
- timer
- responsable del youtube
- tener un objetivo de aprendizaje 

Partimos de la idea de que deberíamos definirnos desde el Por qué, un poco inspirados en el Golden Circle que propone Simon Sinek. 

### Por qué del Chapter

Cómo developers queremos poder tener más opciones para elegir. 
Un espacio para elegir aprender, elegir compartir y preparnos para futuras paths que tomemos. Aumentar nuestro nivel técnico nos permite elegir mejores approach, ejercicios y formas de explicar. Debatir y elegir la forma más adecuada de continuar o iniciar un desarrollo. Conocer más estrategias y coaching nos apoyará en guiar de mejor manera a las estudiantes y entre nosotros.

### Cómo 
Incentivar: 
- Sentido de pertenencia y ownership
- Que nos cueste menos $ aprender
- Asesorarnos
- Investigar 
- Cuestionar 
- Ser más autodidactas. 
- Enfocarnos

### Propuestas: 
 
1. El lead sea rotativo por sede por sesión.
  Esto apoyaría a que los developers de cada sede sean cada vez más Owners del chapter. Luego de la sesión se indicaría cual es la siguiente sede en hacer el Chapter. Esa sede en conjunto decidirá lx Lead, lx Moderadorx, y la agenda. 
2. Tener una agenda antes de cada Chapter
  La agenda debe incluir los tiempos dedicados a cada tema. 
3. Intercalar entre semanas para tener un Chapter de Developer y un Chapter de Coaches
  La idea es que las semanas que toque el Chapter los miércoles sea orientado a Coaches, y los días que toque viernes, este orientado a Developers en general. 
4. Duración de máximo 1 hora (priorizar adecuadamente)
  Creo que nos pasa en todas las sedes, que luego nos llenamos de reuniones o las cosas se van saliendo del Scope. 
4. Ser estrictos con los tiempos (timer)
  Para esto ayudaría que ya sea lx Lead o el Moderadorx
5. Tener un moderadorx designadx
  La idea de tener un moderadorx es que esta persona pueda guiar la conversación y mantenerla dentro de los temas de la agenda.
7. Tener una sección específica de _highliths_
8. Tener una sección (a nominación, cual challenge) de _A ha! moment_

**Comment by RuthSalvador** [comment]
Hola! que buena retrospectiva. 
A mí me gusta la idea que están proponiendo. Como coach me gustaría conocer estrategias de coaching, tips etc; y como developer, hacer proyectos más atractivos. 
Una duda que tengo ahora es sobre que proyectos se van a ver en el siguiente BC, debido a que los del BC ya se han realizado y no veo muy llamativo volver a realizarlos.
Por otro lado no comparto el querer separar el chapter entre developers y coaches, creo que varios developers que no son coaches, tienen muy buenas ideas para el BC. 

PDT: Tengo una duda si la mayoría puede unirse al chapter en el horario coordinado, en los últimos eventos la asistencia ha sido un poco baja, tal vez pueden optar por elegir nuevos horarios.

Gracias

**Comment by lupomontero** [comment]
Hace más de un año que no hay update en este issue... :see_no_evil: ... pero recientemente hemos estado en conversaciones para _re-lanzar_ el hangout mensual del chapter de devs incluyendo tanto a coaches como devs de productos :wink: 

:loudspeaker: El primer hangout de esta nueva serie será el **viernes 15 de Noviembre** de 2019 a las 2:30pm hora de Lima. Para este nuevo hangout **estamos haciendo un CFP (Call For Papers) a todo el chapter de devs para que propongan charlas, temas, ...**

Me tomo la libertad de cerrar este issue, que ya está bien viejito, y continuemos la conversación por Slack...
