### ISSUE TITLE
Añadir gente que falta en Developers Team en GitHub

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/developers.laboratoria.la#6]
Si eres developer o instructor en Laboratoria y no estás en el [equipo del _Developer's Chapter_](https://github.com/orgs/Laboratoria/teams/developers/members) responde a este issue para que te agreguemos.

💪 

cc/ @Laboratoria/developers @Laboratoria/instructores-bootcamp

**Comment by MarciaMillanao** [comment]
Hola @lupomontero  yo no estoy agregada, mi user es @MarciaMillanao, gracias

**Comment by nadiatapm** [comment]
Hola!!!!! @lupomontero  yo no estoy agregada en el equipo del Developer's Chapter, mi user es @nadiatapm .
Gracias :)

**Comment by FabianBravoA** [comment]
Hola!
Agréguenme también.

Muchas gracias

**Comment by lupomontero** [comment]
@MarciaMillanao, @nadiatapm y @FabianBravoA agregados 🎉 

Sería chévere si nos pueden decir su _rol_ (instructor bootcamp/ec, developer, otro...) y ciudad/país.

PS: también es recomendable poner un avatar reconocible y ciudad/país en sus perfiles de GitHub :wink:

Por otro lado, me he tomado la libertad de agregar a @carlosroec y @klujanrosas (instructores de educación continua en Lima) y @merunga (contribuidor a la currícula de JavaScript).

Quién nos falta?

Gracias!

**Comment by Xiovera** [comment]
Hola @lupomontero ...creo que falto yo  @xiovera ...soy TA de Arequipa

**Comment by lupomontero** [comment]
Hola @Xiovera! Agregada al equipo!
