### ISSUE TITLE
Propuestas/sugerencias de charlas para próximos meetups

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/developers.laboratoria.la#7]
Hola todxs,

Acá podemos ir recopilando ideas/propuestas/sugerencias para las charlas de los próximos meetups.

El siguiente meetup en el calendario es Ciudad de México el 7 de diciembre.

cc/ @Laboratoria/developers

**Comment by lupomontero** [comment]
Por ahora tenemos las siguientes propuestas:

* _Uso de Git - Avanzado_ (o algo así) por @FabianBravoA (Santiago)
* _Un viaje por los confines del *protocolo http*_, sugerido por @developerVilchez (Lima)
* ...

Más propuestas?

🇲🇽 Ciudad de México: qué proponen?

**Comment by indie-rok** [comment]
Hola. Me apunto a dar un taller de como crear una REST API sencilla con node.js @lupomontero
